export default {
  OnBoarding: require('../assets/images/TUTORIAL1_IMG.png'),
  OnBoarding2: require('../assets/images/TUTORIAL2_IMG.png'),
  OnBoarding3: require('../assets/images/TUTORIAL3_IMG.png'),
  OnBoarding4: require('../assets/images/onboarding_4.png'),
  OnBoarding5: require('../assets/images/phoneverification2_img.png'),
  OnBoarding7: require('../assets/images/USERFILLED_ICON.png'),

  OnBoarding6: require('../assets/images/SKIPARROW_ICON.png'),
  HomeScreen: require('../assets/images/searchactive_icon.png'),
  HomeScreen2: require('../assets/images/Bookingdisable_icon.png'),
  HomeScreen3: require('../assets/images/helpdisable_icon.png'),
  HomeScreen4: require('../assets/images/userprofile.png'),
  HomeScreen5: require('../assets/images/searchdisable_icon.png'),
  HomeScreen6: require('../assets/images/activecarbottom_icon.png'),
  HomeScreen7: require('../assets/images/helpactive_icon.png'),
  HomeScreen8: require('../assets/images/hOME_img.png'),
  Search: require('../assets/images/myself.png'),
  Search2: require('../assets/images/downarrow.png'),
  Search3: require('../assets/images/Pickup_icon.png'),
  Search4: require('../assets/images/doublearrow.png'),
  Search5: require('../assets/images/location.png'),
  Search6: require('../assets/images/Calender.png'),
  Search7: require('../assets/images/passenger.png'),
  Search8: require('../assets/images/banner_img.png'),
  login: require('../assets/images/DOWNARROW_ICON.png'),
  location: require('../assets/images/Return.png'),
  location2: require('../assets/images/Enroute_img.png'),
  location3: require('../assets/images/updown_icon.png'),
  timer: require('../assets/images/timer.png'),
  downarrow:require('../assets/images/Down.png'),
  profilebackarrow:require('../assets/images/Returnarrow.png'),
  Profilepicture:require('../assets/images/profilepicture.png'),
  Editprofile:require('../assets/images/Editprofile.png'),
  Expandrighticon:require('../assets/images/expandright_icon.png'),
  Settingicon:require('../assets/images/settingicon.png'),
  adress:require('../assets/images/adressicon.png'),
  completekyc:require('../assets/images/completeKYC.png'),
  Refer:require('../assets/images/Refericon.png'),
  logout:require('../assets/images/logout_icon.png'),
  editimg:require('../assets/images/Vector.png'),
  filter:require('../assets/images/filter_icon.png'),
};
