export default {
  LOGIN: 'Login',
  HOME: 'Home',
  TABROUTES: 'TABROUTES',
  SEARCH: 'SEARCH',
  OTPVERIFICATION: 'OTPVERIFICATION',
  HOMESCREEN: 'HOMESCREEN',
  HELP: 'HELP',
  PROFILE: 'PROFILE',
  BOOKINGS: 'BOOKINGS',
  LOCATIONSCREEN: 'LOCATIONSCREEN',
  RIDELIST:"RIDELIST"
};
